apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3
spec:
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: welcome
              mountPath: /usr/share/nginx/html
      volumes:
        - name: welcome
          configMap:
            name: nginx3-welcome
