# shared data
CPU = 1
MEMORY = 512

# The server machine data
SERVER_IP = "192.168.56.110"
SERVER_HOST_NAME = "m0saanS"
SERVER_MACHINE_NAME = "m0saanS"

# The worker machine data
WORKER_IP = "192.168.56.111"
WORKER_HOST_NAME = "m0saanSW"
WORKER_MACHINE_NAME = "m0saanSW"

# Vagrant configuration
Vagrant.configure("2") do |config|

  config.vm.box = "spox/ubuntu-arm"
  config.vm.box_version = "1.0.0"

  # Configuring the server machine
  config.vm.define SERVER_MACHINE_NAME do |server|
    server.vm.hostname = SERVER_HOST_NAME
    server.vm.network "private_network", ip: SERVER_IP
    server.vm.network "forwarded_port", guest: 6443, host: 6443
    server.vm.provider :vmware_desktop do |vmware|
      vmware.vmx["ethernet0.pcislotnumber"] = "160"
      vmware.vmx["ethernet1.pcislotnumber"] = "256"
      vmware.memory = MEMORY
      vmware.cpus = CPU
    end
    server.vm.provision "shell", path: "kubernetes_cluster_setup/k3s_controller_setup.sh", args: [SERVER_IP]
  end

  # Configuring the worker machine
  config.vm.define WORKER_MACHINE_NAME do |worker|
    worker.vm.hostname = WORKER_HOST_NAME
    worker.vm.network "private_network", ip: WORKER_IP
    worker.vm.provider :vmware_desktop do |vmware|
      vmware.vmx["ethernet0.pcislotnumber"] = "160"
      vmware.vmx["ethernet1.pcislotnumber"] = "256"
      vmware.memory = MEMORY
      vmware.cpus = CPU
    end
    worker.vm.provision "shell", path: "kubernetes_cluster_setup/k3s_worker_setup.sh", args: [SERVER_IP]
  end
end