# shared data
CPU = 4
MEMORY = 2048

# The server machine data
SERVER_IP = "192.168.56.110"
SERVER_HOST_NAME = "m0saanS"
SERVER_MACHINE_NAME = "m0saanS"

# Vagrant configuration
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"

  # Configuring the server machine
  config.vm.define SERVER_MACHINE_NAME do |server|

    server.vm.hostname = SERVER_HOST_NAME
    server.vm.network "private_network", ip: SERVER_IP
    server.vm.network "forwarded_port", guest: 6443, host: 6443
    server.vm.network "forwarded_port", guest: 8080, host: 8080
    
    server.vm.provider "virtualbox" do |vmware|
      vmware.memory = MEMORY
      vmware.cpus = CPU
    end
    
    server.vm.provision "shell", path: "kubernetes_cluster_setup/k3s_controller_setup.sh", args: [SERVER_IP]
  end
end
