SERVER_IP = "192.168.56.110"
WORKER_IP = "192.168.56.111"

Vagrant.configure("2") do |config|
  # Define VM configuration for Server
  config.vm.define "eel-orchS" do |server|
    server.vm.box = "ubuntu/focal64"  # Use Ubuntu 20.04 as the OS
    server.vm.hostname = "eel-orchS"
    server.vm.network "private_network", ip: SERVER_IP
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"  # Set memory size
      vb.cpus = 1         # Set CPU count
    end
    server.vm.provision "shell", path: "provision/server.provision.sh", args: [SERVER_IP]
  end
  
  # Define VM configuration for ServerWorker
  config.vm.define "eel-orchSW" do |server_worker|
    server_worker.vm.box = "ubuntu/focal64"  # Use Ubuntu 20.04 as the OS
    server_worker.vm.hostname = "eel-orchSW"
    server_worker.vm.network "private_network", ip: WORKER_IP
    server_worker.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"  # Set memory size
      vb.cpus = 1         # Set CPU count
    end
    server_worker.vm.provision "shell", path: "provision/serverworker.provision.sh", args: [WORKER_IP, SERVER_IP]
  end
end
